export const chapter01 = {
  id: 1,
  title: "Saudi Board Central Collection - Chunk 29 (Questions 270–285)",
  questions: [
    {
      id: 270,
      stem: "During laparoscopic abdominal surgery utilizing carbon dioxide (CO2) pneumoperitoneum with an intra-abdominal pressure maintained at 15 mmHg, which of the following physiological alterations characteristically occurs?",
      image: "",
      options: {
        A: "Irreversible oliguria secondary to intra-abdominal hypertension",
        B: "Decreased intracranial pressure (ICP) and increased cerebral perfusion pressure (CPP)",
        C: "Decreased pulmonary compliance and increased peak airway pressures",
        D: "Decreased splanchnic, renal, and mesenteric blood flow"
      },
      correctAnswer: "D",
      explanation: "Pneumoperitoneum generated by CO2 insufflation to pressures >= 15 mmHg compresses the splanchnic venous and arterial vascular beds, resulting in a **significant reduction in splanchnic, mesenteric, hepatic, and renal cortical blood flow**[cite: 21]. Renal perfusion and glomerular filtration rate decrease, producing transient, reversible oliguria mediated by direct compression of renal parenchyma and renal veins, alongside increased release of renin, aldosterone, and vasopressin[cite: 21]. Cephalad displacement of the diaphragm reduces functional residual capacity and thoracoabdominal compliance, which **increases (not decreases) peak and plateau airway pressures**[cite: 21]. Elevated intra-abdominal and intrathoracic pressures impede cerebral venous return, leading to **increased ICP and potentially decreased CPP**[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Ch. 68: Laparoscopic Surgery; Barash Clinical Anesthesia, 8th Ed., Ch. 42)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 271,
      stem: "A 60-year-old male is scheduled for a right-sided pneumonectomy. A size 39 Fr left-sided double-lumen endobronchial tube (DLT) is placed. Both cuffs are inflated. When ventilating through the bronchial lumen with the tracheal lumen clamped, bilateral breath sounds are auscultated. When ventilating through the tracheal lumen with the bronchial lumen clamped, no breath sounds are heard. What is the most appropriate corrective intervention?",
      image: "",
      options: {
        A: "Downsize the DLT to a 37 Fr tube",
        B: "Deflate the bronchial cuff and advance the DLT further into the left mainstem bronchus",
        C: "Withdraw the DLT by 2 to 3 cm",
        D: "Upsize the DLT to a 41 Fr tube to eliminate an air leak"
      },
      correctAnswer: "B",
      explanation: "When ventilating through the bronchial lumen yields bilateral breath sounds and ventilating through the tracheal lumen produces no air entry, the **DLT is positioned out too far** (proximal)[cite: 18, 21]. The bronchial tip is still residing in the distal trachea above the carina, allowing gas from the bronchial lumen to ventilate both mainstem bronchi[cite: 18, 21]. Furthermore, the inflated bronchial cuff is occluding the lower trachea while the tracheal lumen is trapped between the two inflated cuffs, preventing gas exit[cite: 18, 21]. The corrective action is to **deflate both cuffs and advance the tube further until the bronchial tip enters the left mainstem bronchus**, confirming placement under flexible fiberoptic bronchoscopy[cite: 18, 21]. *(References: Barash Clinical Anesthesia, 8th Ed., p. 1043; Miller's Anesthesia, 9th Ed., Ch. 66)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 272,
      stem: "A 62-year-old patient with documented stable angina and type 2 diabetes mellitus managed on oral hypoglycemic agents (non-insulin dependent) is scheduled for elective total knee arthroplasty. According to the Revised Cardiac Risk Index (RCRI / Lee Criteria), what is his assigned score and corresponding estimated risk of major perioperative cardiac events?",
      image: "",
      options: {
        A: "RCRI score 0 (0.4% risk)",
        B: "RCRI score 1 (1.0% risk)",
        C: "RCRI score 2 (2.4% risk)",
        D: "RCRI score 3 (5.4% risk)"
      },
      correctAnswer: "B",
      explanation: "The Revised Cardiac Risk Index (RCRI) assigns 1 point each for six independent risk predictors[cite: 21]: (1) High-risk surgery (intraperitoneal, intrathoracic, or suprainguinal vascular)[cite: 21]; (2) **Ischemic heart disease** (history of MI, positive stress test, angina, nitrate use, or pathological Q waves)[cite: 21]; (3) History of congestive heart failure[cite: 21]; (4) History of cerebrovascular disease[cite: 21]; (5) **Diabetes mellitus requiring preoperative insulin therapy**[cite: 21]; and (6) Preoperative serum creatinine > 2.0 mg/dL (176 mcmol/L)[cite: 21]. Total knee arthroplasty is an intermediate-risk procedure (0 points)[cite: 21]. This patient receives 1 point for ischemic heart disease and 0 points for diabetes (because insulin is not required)[cite: 21]. An **RCRI score of 1 corresponds to an estimated 1.0% risk** of major cardiac complications (cardiac arrest, MI, complete heart block, or pulmonary edema)[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Table 38-3, p. 1094; Lee et al., Circulation 1999)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 273,
      stem: "A 54-year-old male presents with acute bowel perforation, peritonitis, and septic shock requiring emergency exploratory laparotomy. His medical history includes an acute myocardial infarction 4 months ago and physical examination reveals signs of congestive heart failure (pulmonary crackles and peripheral edema). What is the most appropriate next step in clinical management?",
      image: "",
      options: {
        A: "Proceed immediately to the operating room for emergency laparotomy with invasive monitoring and active resuscitation",
        B: "Transfer the patient to the cardiac catheterization suite for emergent coronary angiography",
        C: "Postpone surgery to perform a pharmacological myocardial perfusion nuclear stress test",
        D: "Admit to the coronary care unit for 48 hours of medical cardiac optimization"
      },
      correctAnswer: "A",
      explanation: "According to the ACC/AHA Guidelines on Perioperative Cardiovascular Evaluation, when a patient presents for **emergency noncardiac surgery** (where delay will lead to irreversible morbidity or death, as in peritonitis from viscus perforation), **no further cardiovascular diagnostic testing is indicated**[cite: 14, 21]. Preoperative stress testing, nuclear scintigraphy, or coronary angiography will delay definitive surgical control of sepsis and are contraindicated[cite: 21]. The patient should **proceed directly to the operating room with invasive hemodynamic monitoring** (arterial line and central venous line), rapid cardiopulmonary optimization, and careful titration of inotropes and vasopressors[cite: 14, 21]. *(References: ACC/AHA Perioperative Cardiovascular Guidelines; Stoelting's Anesthesia and Co-Existing Disease, 8th Ed., Ch. 1)*[cite: 14].",
      explanationImages: []
    },
    {
      id: 274,
      stem: "During a preoperative anesthetic assessment, a 48-year-old patient states that he is an avid swimmer capable of swimming continuously for 3 hours at a vigorous pace without chest pain, palpitations, or shortness of breath. What is his estimated functional capacity in Metabolic Equivalents of Task (METs)?",
      image: "",
      options: {
        A: "4 METs",
        B: "6 METs",
        C: "8 METs",
        D: ">= 10 METs"
      },
      correctAnswer: "D",
      explanation: "One Metabolic Equivalent of Task (1 MET) represents baseline resting adult oxygen consumption (3.5 mL O2/kg/min)[cite: 21]. Functional capacity is stratified as poor (< 4 METs), moderate (4 to 7 METs), and excellent (> 7 to 10 METs)[cite: 21]. Strenuous athletic participation—such as **vigorous lap swimming**, competitive basketball, running, or heavy cycling—requires **>= 10 METs** of oxygen consumption[cite: 21]. An individual able to swim continuously for multiple hours exhibits excellent functional cardiopulmonary reserve (>= 10 METs), which correlates with a low risk of perioperative cardiac morbidity[cite: 21]. *(References: ACC/AHA Guideline on Perioperative Cardiovascular Evaluation; Miller's Anesthesia, 9th Ed., Ch. 38)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 275,
      stem: "According to discharge criteria for ambulatory day surgery, which of the following patients has the highest clinical risk of postoperative urinary retention and failing to void spontaneously prior to discharge?",
      image: "",
      options: {
        A: "A 40-year-old female who underwent knee arthroscopy under general anesthesia with minimal fluids",
        B: "A male patient who underwent inguinal hernia repair under spinal anesthesia using 10 mg hyperbaric bupivacaine",
        C: "A female patient who received 10 mg intravenous morphine following laparoscopic cholecystectomy",
        D: "A 25-year-old male undergoing excision of a sebaceous cyst under local infiltration"
      },
      correctAnswer: "B",
      explanation: "Postoperative urinary retention (POUR) in ambulatory surgery is strongly correlated with male gender, age > 50 years, anorectal or hernia procedures, and **spinal anesthesia using long-acting local anesthetics (e.g., bupivacaine doses > 7–10 mg)**[cite: 19, 21]. Spinal bupivacaine produces prolonged blockade of the parasympathetic sacral nerve roots (S2–S4), which inhibits detrusor muscle contractility long after lower-extremity motor function has returned[cite: 19, 21]. The combination of **male gender, inguinal hernia surgery, and 10 mg spinal bupivacaine** creates the highest risk profile for urinary retention, often necessitating bladder catheterization and mandatory voiding before discharge[cite: 19, 21]. *(References: Miller's Basics of Anesthesia, 7th Ed., p. 686; Barash Clinical Anesthesia, 8th Ed., Ch. 57, p. 1617)*[cite: 19, 21].",
      explanationImages: []
    },
    {
      id: 276,
      stem: "During the strain phase (Phase II) of a sustained Valsalva maneuver (forced expiration against a closed glottis with high intrathoracic pressure), which physiological hemodynamic alteration is characteristically observed?",
      image: "",
      options: {
        A: "Significant increase in cardiac stroke volume and cardiac output",
        B: "Marked increase in central venous pressure accompanied by decreased venous return",
        C: "Decrease in systemic vascular resistance mediated by vagal discharge",
        D: "Decrease in intrathoracic and right atrial pressures"
      },
      correctAnswer: "B",
      explanation: "A forced expiration against a closed glottis sharply increases intrathoracic pressure (often up to 30–40 mmHg)[cite: 21]. This elevates measured **central venous pressure (CVP)** and right atrial pressure, compressing the thoracic vena cava and **markedly reducing venous return (preload) to both the right and left ventricles**[cite: 21]. Consequently, stroke volume, mean arterial pressure, and cardiac output fall precipitously during Phase II of the maneuver, which subsequently stimulates arterial baroreceptors to trigger reflex tachycardia and peripheral vasoconstriction[cite: 21]. *(References: Stoelting's Pharmacology and Physiology in Anesthetic Practice, 6th Ed., Ch. Cardiovascular Physiology; Barash Clinical Anesthesia, 8th Ed., Ch. 16)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 277,
      stem: "What is the physiological term defining the fraction of inspired minute ventilation that enters the respiratory zone (respiratory bronchioles and alveoli) to participate actively in pulmonary gas exchange?",
      image: "",
      options: {
        A: "Anatomic dead space volume",
        B: "Effective tidal volume",
        C: "Total minute ventilation",
        D: "Alveolar ventilation"
      },
      correctAnswer: "D",
      explanation: "**Alveolar ventilation ($V_A$)** is defined as the volume of fresh inspired gas that reaches the gas-exchanging units of the lung—the respiratory bronchioles, alveolar ducts, and alveoli—per unit time[cite: 21]. It is calculated as: $$\\dot{V}_A = (V_T - V_D) \\times f$$ where $V_T$ is tidal volume, $V_D$ is physiologic dead space (conducting airways + non-perfused alveoli), and $f$ is respiratory rate[cite: 21]. In a healthy 70 kg adult, alveolar ventilation is approximately 4 to 5 L/min at rest, matching pulmonary capillary blood flow to produce a global ventilation/perfusion ($V/Q$) ratio near 1.0[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Ch. Respiratory Physiology, p. 446; Barash Clinical Anesthesia, 8th Ed., Ch. 11)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 278,
      stem: "Which standardized safety engineering system is incorporated into pipeline hoses and anesthesia workstation wall connections to prevent the accidental misconnection of non-interchangeable hospital medical gas pipelines?",
      image: "",
      options: {
        A: "Pin Index Safety System (PISS)",
        B: "Diameter Index Safety System (DISS)",
        C: "Oxygen Failure Safety Device (Fail-Safe)",
        D: "Hypoxic Guard Proportioning System"
      },
      correctAnswer: "B",
      explanation: "The **Diameter Index Safety System (DISS)** utilizes distinct, dimensionally non-interchangeable threaded connections (differing bore and thread diameters) to connect **central hospital pipeline gas supply hoses to the back of the anesthesia workstation** and wall terminal outlets, preventing cross-connection of pipeline gases[cite: 21]. In contrast, the **Pin Index Safety System (PISS)** uses specific pin-hole coordinate configurations on the yoke flush valves to prevent misconnecting **high-pressure gas cylinders (E-cylinders)** to the wrong hanger yoke[cite: 21]. The oxygen failure safety device (fail-safe valve) shuts off or proportionally reduces nitrous oxide if oxygen pipeline pressure falls below ~30 psig[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Ch. Anesthesia Delivery Systems, p. 752; Dorsch and Dorsch: Understanding Anesthesia Equipment, 5th Ed.)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 279,
      stem: "A patient with an implantable cardioverter-defibrillator (ICD) is scheduled for elective open abdominal surgery where unipolar electrocautery will be used above the umbilicus. According to ASA guidelines for the perioperative management of patients with cardiac implantable electronic devices (CIEDs), what is the most appropriate management of the ICD?",
      image: "",
      options: {
        A: "Reprogram the ICD to an asynchronous pacing mode (e.g., VOO) for all surgical cases regardless of cautery site",
        B: "Temporarily suspend/deactivate the tachyarrhythmia detection and shock therapy (via magnet placement or device programmer) during electrocautery",
        C: "Turn off all bradycardia pacing and tachyarrhythmia therapies permanently before entering the operating room",
        D: "Leave the ICD active without modification since modern devices are immune to electromagnetic interference"
      },
      correctAnswer: "B",
      explanation: "Electromagnetic interference (EMI) from unipolar electrocautery (particularly within 15 cm of the pulse generator or above the umbilicus) can be oversensed by an ICD as ventricular fibrillation or tachycardia, triggering an **inappropriate intraoperative high-energy shock** or causing electrical reset[cite: 21]. Standard practice dictates that **tachyarrhythmia detection and shock functions must be temporarily suspended (disabled)** prior to surgery by placing an appropriate clinical magnet over the header or via non-invasive programmer interrogation[cite: 21]. External defibrillation equipment (pads placed on the chest) and pacing capability must be immediately available throughout the case, and full ICD antiarrhythmic monitoring must be reactivated in the PACU prior to discharge[cite: 21]. *(References: ASA Practice Advisory for the Perioperative Management of Patients with CIEDs; Miller's Anesthesia, 9th Ed., Ch. 38)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 280,
      stem: "Which of the following metabolic and hematologic complications occurs with an increased incidence in preterm neonates (< 37 weeks of gestational age) compared to full-term infants?",
      image: "",
      options: {
        A: "Severe persistent hyperglycemia",
        B: "Acute hypercalcemia",
        C: "Hyperbilirubinemia",
        D: "Elevated serum albumin concentrations (> 35 g/L)"
      },
      correctAnswer: "C",
      explanation: "Preterm neonates (< 37 weeks' gestation) frequently develop **neonatal unconjugated hyperbilirubinemia** due to shortened red blood cell lifespan, increased bilirubin load, and **developmental immaturity of hepatic uridine diphosphate glucuronosyltransferase (UGT1A1) activity**[cite: 21]. Deficient glucuronide conjugation coupled with low serum albumin levels (decreased bilirubin binding capacity) elevates circulating free unconjugated bilirubin, placing the preterm neonate at high risk for bilirubin encephalopathy (kernicterus)[cite: 21]. Preterm infants are also prone to hypoglycemia (due to small hepatic glycogen stores) and hypocalcemia, rather than hyperglycemia or hypercalcemia[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Table 93-1; Smith's Anesthesia for Infants and Children, 9th Ed., Ch. Neonatal Physiology)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 281,
      stem: "A 53-year-old male undergoing laparoscopic sleeve gastrectomy is induced under general anesthesia. Following carbon dioxide insufflation, the operating table is positioned into steep reverse Trendelenburg (head-up). What is the primary compensatory hemodynamic response observed in this position?",
      image: "",
      options: {
        A: "Compensatory increase in heart rate (HR) and systemic vascular resistance (SVR)",
        B: "Marked increase in cardiac index (CI)",
        C: "Significant elevation in central venous pressure and ventricular preload",
        D: "Immediate decrease in systemic vascular resistance"
      },
      correctAnswer: "A",
      explanation: "In the reverse Trendelenburg (head-up) position, gravity causes blood pooling in the dependent venous capacitance vessels of the lower extremities and pelvis, which is compounded by pneumoperitoneum-induced compression of the inferior vena cava[cite: 21]. This results in a **decrease in venous return, central blood volume, ventricular preload, and cardiac output/index**[cite: 21]. In response to the unloading of carotid sinus and aortic arch baroreceptors, sympathetic tone increases while vagal tone decreases, triggering a **compensatory reflex increase in heart rate (tachycardia) and elevated systemic vascular resistance (SVR)** to maintain mean arterial pressure[cite: 21]. *(References: Faust's Anesthesiology Review, 5th Ed., Ch. 165, p. 398; Morgan & Mikhail's Clinical Anesthesiology, 7th Ed., p. 1072; Miller's Anesthesia, 9th Ed., p. 2167)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 282,
      stem: "A 35-year-old female with Graves' disease undergoes emergency exploratory laparotomy for trauma. In the PACU, she acutely develops severe hyperpyrexia (temperature 40.2°C), marked sinus tachycardia (HR 165 bpm), agitation, and severe systolic hypertension. Thyroid storm is diagnosed. Which of the following medications is a primary first-line antithyroid drug indicated to inhibit the synthesis of new thyroid hormones?",
      image: "",
      options: {
        A: "Propylthiouracil (PTU)",
        B: "Intravenous dantrolene sodium",
        C: "Intravenous octreotide",
        D: "Intravenous phentolamine"
      },
      correctAnswer: "A",
      explanation: "Thyroid storm is a life-threatening hypermetabolic crisis precipitated by surgical trauma, infection, or noncompliance in patients with thyrotoxicosis[cite: 21]. Definitive pharmacologic treatment involves: (1) **Inhibition of new hormone synthesis using thionamides, specifically Propylthiouracil (PTU)** (600–1000 mg PO/PR load, then 200 mg q4h), which also inhibits peripheral conversion of T4 to active T3[cite: 21]; (2) Hemodynamic control with beta-adrenergic antagonists (esmolol or propranolol); (3) Inhibition of thyroid hormone release with inorganic iodine (Lugol's solution or potassium iodide, given at least 1 hour after PTU); and (4) High-dose glucocorticoids (hydrocortisone or dexamethasone) to decrease peripheral T4-to-T3 conversion and treat relative adrenal insufficiency[cite: 21]. Dantrolene treats malignant hyperthermia, octreotide treats carcinoid crisis, and phentolamine treats pheochromocytoma[cite: 21]. *(References: Stoelting's Anesthesia and Co-Existing Disease, 8th Ed., Ch. 18; Barash Clinical Anesthesia, 8th Ed., Ch. 49)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 283,
      stem: "In a healthy, hemodynamically stable 70 kg adult with a pulmonary artery catheter in place, which of the following calculated oxy-hemodynamic parameters represents an abnormal physiological value?",
      image: "",
      options: {
        A: "Cardiac output of 5.0 L/min",
        B: "Arterial oxygen content (CaO2) of 18 mL/dL",
        C: "Mixed venous oxygen content (CvO2) of 14 mL/dL",
        D: "Arteriovenous oxygen content difference (C[a-v]O2) of 12 mL/dL"
      },
      correctAnswer: "D",
      explanation: "Normal adult cardiopulmonary reference values include[cite: 21]:\n* Cardiac output: 4.0 to 6.5 L/min (average ~5.0 L/min)[cite: 21].\n* Arterial oxygen content ($CaO_2$): 16 to 20 mL/dL (average ~18 mL/dL)[cite: 21].\n* Mixed venous oxygen content ($C\\bar{v}O_2$): 13 to 15 mL/dL (average ~14 mL/dL)[cite: 21].\n* Mixed venous oxygen saturation ($S\\bar{v}O_2$): 70% to 75%[cite: 21].\n* **Normal arteriovenous oxygen content difference ($C[a-v]O_2$) is 3 to 5 mL/dL (average ~4 mL/dL)**[cite: 21].\nAn arteriovenous oxygen difference of **12 mL/dL is distinctly abnormal**, signifying severe low-output shock, profound hypoperfusion, or pathologically exaggerated peripheral oxygen extraction[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Table 45-7, p. 1384; Morgan & Mikhail's Clinical Anesthesiology, 7th Ed., Ch. 21)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 284,
      stem: "According to Poiseuille's law of laminar flow, which of the following peripheral intravenous cannulas will achieve the fastest gravity-driven fluid infusion rate during emergent volume resuscitation in a trauma patient with hemorrhagic shock?",
      image: "",
      options: {
        A: "16-gauge, 1.5-inch catheter",
        B: "14-gauge, 1.5-inch catheter",
        C: "16-gauge, 2.0-inch catheter",
        D: "14-gauge, 2.0-inch catheter"
      },
      correctAnswer: "B",
      explanation: "Fluid flow through an intravenous cannula is described by the Hagen-Poiseuille equation[cite: 21]:\n$$Q = \\frac{\\pi \\cdot \\Delta P \\cdot r^4}{8 \\cdot \\eta \\cdot L}$$\nwhere flow rate ($Q$) is directly proportional to the fourth power of the internal radius ($r^4$) and inversely proportional to cannula length ($L$)[cite: 21]. Therefore, maximizing infusion velocity requires the **largest internal radius (14-gauge)** paired with the **shortest catheter length (1.5 inches)**[cite: 21]. A 14-gauge, 1.5-inch catheter provides approximately 300 to 350 mL/min of gravity crystalloid flow, which is greater than a longer 2.0-inch catheter or narrower 16-gauge cannula[cite: 21]. *(References: Barash Clinical Anesthesia, 8th Ed., Ch. 22; Miller's Anesthesia, 9th Ed., Ch. Vascular Access)*[cite: 21].",
      explanationImages: []
    },
    {
      id: 285,
      stem: "A 15-year-old female undergoes surgical resection of a suprasellar craniopharyngioma. Postoperatively, she abruptly develops high-volume, dilute polyuria (urine output > 5 mL/kg/h with specific gravity < 1.005). What characteristic serum electrolyte abnormality is expected in this setting of untreated central diabetes insipidus?",
      image: "",
      options: {
        A: "Hypernatremia",
        B: "Severe hyperkalemia",
        C: "Hyponatremia",
        D: "Hypocalcemia"
      },
      correctAnswer: "A",
      explanation: "Surgical manipulation of the hypothalamic-hypophyseal tract damages the posterior pituitary, abolishing arginine vasopressin (ADH) secretion and precipitating acute central diabetes insipidus (CDI)[cite: 14, 21]. Absence of ADH renders the renal collecting ducts impermeable to water, leading to copious free-water clearance (urine osmolality < 200 mOsm/kg)[cite: 11, 21]. The rapid loss of electrolyte-free water results in a contracted, hyperosmolar intravascular space characteristically manifesting as **hypernatremia (serum sodium > 145–150 mEq/L)** and elevated serum osmolality (> 300 mOsm/kg)[cite: 14, 21]. In contrast, SIADH and cerebral salt wasting syndrome produce hyponatremia[cite: 21]. *(References: Miller's Anesthesia, 9th Ed., Ch. Fluid and Electrolyte Disorders, Table 28-1; Morgan & Mikhail's Clinical Anesthesiology, 7th Ed., p. 616)*[cite: 15, 21].",
      explanationImages: []
    }
  ]
};